# Generated by Django 3.2.5 on 2021-07-24 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
