# Generated by Django 3.2.5 on 2021-07-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_remove_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagecontent',
            field=models.ImageField(blank=True, null=True, upload_to='content'),
        ),
    ]
